apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sccluster
  region: ap-south-1

nodeGroups:
   - name: node1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: mykey

   - name: node-mixed
     minSize: 1
     maxSize: 3
     instancesDistribution:
       maxPrice: 0.017
       instanceTypes: ["t2.micro"] 
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: mykey